// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:2.2.0.0
//      SpecFlow Generator Version:2.2.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace FacebookAutomationTest.Features
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "2.2.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("AccountRegistrationFeature")]
    public partial class AccountRegistrationFeatureFeature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "AccountRegistrationFeature.feature"
#line hidden
        
        [NUnit.Framework.OneTimeSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "AccountRegistrationFeature", "\tAs user \r\n\tI want to be able to register new account\r\n\tSo that I can use this ac" +
                    "count to login the system", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.OneTimeTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public virtual void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("_Sign up successfully with correct required fields using email")]
        [NUnit.Framework.CategoryAttribute("regression")]
        public virtual void _SignUpSuccessfullyWithCorrectRequiredFieldsUsingEmail()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("_Sign up successfully with correct required fields using email", new string[] {
                        "regression"});
#line 7
this.ScenarioSetup(scenarioInfo);
#line 8
 testRunner.Given("I open the main page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
            TechTalk.SpecFlow.Table table1 = new TechTalk.SpecFlow.Table(new string[] {
                        "Fname",
                        "Sname",
                        "Email",
                        "Password",
                        "Gender"});
            table1.AddRow(new string[] {
                        "AutoName",
                        "AutoSurname",
                        "autoemail@gmail.com",
                        "AutoPass!1",
                        "M"});
#line 9
 testRunner.And("I have entered the following values to the registration form", ((string)(null)), table1, "And ");
#line 12
 testRunner.When("I click create account button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 13
 testRunner.Then("I see a pop-up with \'Confirm Your Birthday\' title", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("_Sign up successfully with correct required fields using phone number")]
        [NUnit.Framework.CategoryAttribute("regression")]
        public virtual void _SignUpSuccessfullyWithCorrectRequiredFieldsUsingPhoneNumber()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("_Sign up successfully with correct required fields using phone number", new string[] {
                        "regression"});
#line 16
this.ScenarioSetup(scenarioInfo);
#line 17
 testRunner.Given("I open the main page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
            TechTalk.SpecFlow.Table table2 = new TechTalk.SpecFlow.Table(new string[] {
                        "Fname",
                        "Sname",
                        "Email",
                        "Password",
                        "Gender"});
            table2.AddRow(new string[] {
                        "AutoName",
                        "AutoSurname",
                        "34987654321",
                        "AutoPass!1",
                        "M"});
#line 18
 testRunner.And("I have entered the following values to the registration form without reentering e" +
                    "mail phone field", ((string)(null)), table2, "And ");
#line 21
 testRunner.When("I click create account button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 22
 testRunner.Then("I see a pop-up with \'Confirm Your Birthday\' title", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Sign up first name error correctness")]
        [NUnit.Framework.CategoryAttribute("regression")]
        public virtual void SignUpFirstNameErrorCorrectness()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Sign up first name error correctness", new string[] {
                        "regression"});
#line 25
this.ScenarioSetup(scenarioInfo);
#line 26
 testRunner.Given("I open the main page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 27
 testRunner.When("I click create account button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 28
 testRunner.Then("I see a \"What’s your name?\" first name error", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Sign up second name error correctness")]
        [NUnit.Framework.CategoryAttribute("regression")]
        public virtual void SignUpSecondNameErrorCorrectness()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Sign up second name error correctness", new string[] {
                        "regression"});
#line 31
this.ScenarioSetup(scenarioInfo);
#line 32
 testRunner.Given("I open the main page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
            TechTalk.SpecFlow.Table table3 = new TechTalk.SpecFlow.Table(new string[] {
                        "Fname",
                        "Sname",
                        "Email",
                        "Password",
                        "Gender"});
            table3.AddRow(new string[] {
                        "AutoName12",
                        "",
                        "asdasd@gmail.com",
                        "AutoPass!1",
                        "M"});
#line 33
 testRunner.And("I have entered the following values to the registration form", ((string)(null)), table3, "And ");
#line 36
 testRunner.When("I click create account button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 37
 testRunner.Then("I see a \"What’s your name?\" second name error", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Sign up phone mail error correctness")]
        [NUnit.Framework.CategoryAttribute("regression")]
        public virtual void SignUpPhoneMailErrorCorrectness()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Sign up phone mail error correctness", new string[] {
                        "regression"});
#line 40
this.ScenarioSetup(scenarioInfo);
#line 41
 testRunner.Given("I open the main page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
            TechTalk.SpecFlow.Table table4 = new TechTalk.SpecFlow.Table(new string[] {
                        "Fname",
                        "Sname",
                        "Email",
                        "Password",
                        "Gender"});
            table4.AddRow(new string[] {
                        "AutoName12",
                        "AutoSurname12",
                        "",
                        "AutoPass!1",
                        "M"});
#line 42
 testRunner.And("I have entered the following values to the registration form without reentering e" +
                    "mail phone field", ((string)(null)), table4, "And ");
#line 45
 testRunner.When("I click create account button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 46
 testRunner.Then("I see a \"You\'ll use this when you log in and if you ever need to reset your passw" +
                    "ord.\" phone mail error", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Sign up password error correctness")]
        [NUnit.Framework.CategoryAttribute("regression")]
        public virtual void SignUpPasswordErrorCorrectness()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Sign up password error correctness", new string[] {
                        "regression"});
#line 49
this.ScenarioSetup(scenarioInfo);
#line 50
 testRunner.Given("I open the main page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
            TechTalk.SpecFlow.Table table5 = new TechTalk.SpecFlow.Table(new string[] {
                        "Fname",
                        "Sname",
                        "Email",
                        "Password",
                        "Gender"});
            table5.AddRow(new string[] {
                        "AutoName12",
                        "AutoSurname12",
                        "asdasd@gmail.com",
                        "",
                        "M"});
#line 51
 testRunner.And("I have entered the following values to the registration form", ((string)(null)), table5, "And ");
#line 54
 testRunner.When("I click create account button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 55
 testRunner.Then("I see a \"Enter a combination of at least six numbers, letters and punctuation mar" +
                    "ks (like ! and &).\" password error", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Sign up gender error correctness")]
        [NUnit.Framework.CategoryAttribute("regression")]
        public virtual void SignUpGenderErrorCorrectness()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Sign up gender error correctness", new string[] {
                        "regression"});
#line 58
this.ScenarioSetup(scenarioInfo);
#line 59
 testRunner.Given("I open the main page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
            TechTalk.SpecFlow.Table table6 = new TechTalk.SpecFlow.Table(new string[] {
                        "Fname",
                        "Sname",
                        "Email",
                        "Password",
                        "Gender"});
            table6.AddRow(new string[] {
                        "AutoName12",
                        "AutoSurname12",
                        "asdasd@gmail.com",
                        "AutoPass!1",
                        ""});
#line 60
 testRunner.And("I have entered the following values to the registration form", ((string)(null)), table6, "And ");
#line 63
 testRunner.When("I click create account button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 64
 testRunner.Then("I see a \"Please choose a gender. You can change who can see this later.\" gender e" +
                    "rror", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Sign up password format error correctness")]
        [NUnit.Framework.CategoryAttribute("regression")]
        [NUnit.Framework.TestCaseAttribute("aaaaaa", null)]
        [NUnit.Framework.TestCaseAttribute("000000", null)]
        public virtual void SignUpPasswordFormatErrorCorrectness(string password, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "regression"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Sign up password format error correctness", @__tags);
#line 67
this.ScenarioSetup(scenarioInfo);
#line 68
 testRunner.Given("I open the main page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 69
 testRunner.And(string.Format("I have entered default values in the fields and specific with \'{0}\' password", password), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 70
 testRunner.When("I click create account button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 71
 testRunner.And("I click Yes button on birthday confirmation window", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 72
 testRunner.Then("I see a \"Please choose a more secure password. It should be longer than 6 charact" +
                    "ers, unique to you, and difficult for others to guess.\" general error", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Sign up password length error correctness")]
        [NUnit.Framework.CategoryAttribute("regression")]
        [NUnit.Framework.TestCaseAttribute("12345", null)]
        public virtual void SignUpPasswordLengthErrorCorrectness(string password, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "regression"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Sign up password length error correctness", @__tags);
#line 79
this.ScenarioSetup(scenarioInfo);
#line 80
 testRunner.Given("I open the main page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 81
 testRunner.And(string.Format("I have entered default values in the fields and specific with \'{0}\' password", password), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 82
 testRunner.When("I click create account button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 83
 testRunner.And("I click Yes button on birthday confirmation window", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 84
 testRunner.Then("I see a \"Your password must be at least 6 characters long. Please try another.\" g" +
                    "eneral error", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Sign up email and phone format error correctness")]
        [NUnit.Framework.CategoryAttribute("regression")]
        [NUnit.Framework.TestCaseAttribute("abc", null)]
        [NUnit.Framework.TestCaseAttribute("abc@", null)]
        [NUnit.Framework.TestCaseAttribute("abc@de", null)]
        [NUnit.Framework.TestCaseAttribute("341234567a", null)]
        [NUnit.Framework.TestCaseAttribute("123456789", null)]
        [NUnit.Framework.TestCaseAttribute("34!2345689", null)]
        public virtual void SignUpEmailAndPhoneFormatErrorCorrectness(string emailphone, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "regression"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Sign up email and phone format error correctness", @__tags);
#line 90
this.ScenarioSetup(scenarioInfo);
#line 91
 testRunner.Given("I open the main page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 92
 testRunner.And(string.Format("I have entered default values in the fields and specific with \'{0}\' email or phon" +
                        "e value", emailphone), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 93
 testRunner.When("I click create account button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 94
 testRunner.Then("I see a \"Please enter a valid mobile number or email address.\" password error", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Sign up name format error correctness for characters not allowed reason")]
        [NUnit.Framework.CategoryAttribute("regression")]
        [NUnit.Framework.TestCaseAttribute("abc", "123", null)]
        [NUnit.Framework.TestCaseAttribute("123", "xyz", null)]
        public virtual void SignUpNameFormatErrorCorrectnessForCharactersNotAllowedReason(string firstname, string secondname, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "regression"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Sign up name format error correctness for characters not allowed reason", @__tags);
#line 105
this.ScenarioSetup(scenarioInfo);
#line 106
 testRunner.Given("I open the main page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 107
 testRunner.And(string.Format("I have entered default values in the fields and specific with \'{0}\' first name an" +
                        "d \'{1}\' second name values", firstname, secondname), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 108
 testRunner.When("I click create account button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 109
 testRunner.And("I click Yes button on birthday confirmation window", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 110
 testRunner.Then("I see a \"This name has certain characters that aren\'t allowed. Learn more about o" +
                    "ur name policies.\" general error", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Sign up name format error correctness for email reason")]
        [NUnit.Framework.CategoryAttribute("regression")]
        [NUnit.Framework.TestCaseAttribute("!@_", "xyz", null)]
        [NUnit.Framework.TestCaseAttribute("abc", "!@_", null)]
        public virtual void SignUpNameFormatErrorCorrectnessForEmailReason(string firstname, string secondname, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "regression"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Sign up name format error correctness for email reason", @__tags);
#line 117
this.ScenarioSetup(scenarioInfo);
#line 118
 testRunner.Given("I open the main page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 119
 testRunner.And(string.Format("I have entered default values in the fields and specific with \'{0}\' first name an" +
                        "d \'{1}\' second name values", firstname, secondname), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 120
 testRunner.When("I click create account button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 121
 testRunner.And("I click Yes button on birthday confirmation window", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 122
 testRunner.Then("I see a \"It looks like you entered a mobile number or email. Please enter your na" +
                    "me.\" general error", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Sign up name celebrity error correctness")]
        [NUnit.Framework.CategoryAttribute("regression")]
        [NUnit.Framework.TestCaseAttribute("John", "Cena", null)]
        [NUnit.Framework.TestCaseAttribute("Barak", "Obama", null)]
        public virtual void SignUpNameCelebrityErrorCorrectness(string firstname, string secondname, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "regression"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Sign up name celebrity error correctness", @__tags);
#line 129
this.ScenarioSetup(scenarioInfo);
#line 130
 testRunner.Given("I open the main page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 131
 testRunner.And(string.Format("I have entered default values in the fields and specific with \'{0}\' first name an" +
                        "d \'{1}\' second name values", firstname, secondname), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 132
 testRunner.When("I click create account button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 133
 testRunner.And("I click Yes button on birthday confirmation window", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 134
 testRunner.Then("I see a \"It seems like you\'re trying to create a profile for a celebrity. Learn m" +
                    "ore about our name policies, including how to let us know if this is the name yo" +
                    "u use in everyday life, what your friends call you.\" general error", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
